/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baling;

import baling.secion;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author joyad
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() { 
        initComponents();
        initDatabase();
        populateTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelFirstName = new javax.swing.JLabel();
        LabelLastName = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelUserName = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        InputFirstName = new javax.swing.JTextField();
        InputLastName = new javax.swing.JTextField();
        InputEmail = new javax.swing.JTextField();
        InputUserName = new javax.swing.JTextField();
        InputPhone = new javax.swing.JTextField();
        InputPassword = new javax.swing.JTextField();
        ButtonInsert = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonSearch = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableListUser = new javax.swing.JTable();
        buttonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelFirstName.setText("FirstName");

        LabelLastName.setText("LastName");

        LabelEmail.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("USER");

        LabelPhone.setText("Phone");

        LabelUserName.setText("UserName");

        LabelPassword.setText("Password");

        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });

        InputUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputUserNameActionPerformed(evt);
            }
        });

        ButtonInsert.setText("INSERT");
        ButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("UPDATE");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonSearch.setText("SEARCH");
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        ButtonDelete.setText("DELETE");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        TableListUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableListUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "LastName", "Email", "Phone", "UserName", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableListUser.setGridColor(new java.awt.Color(102, 102, 102));
        TableListUser.setShowGrid(true);
        TableListUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableListUser);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(ButtonInsert)
                .addGap(62, 62, 62)
                .addComponent(ButtonUpdate)
                .addGap(78, 78, 78)
                .addComponent(ButtonSearch)
                .addGap(62, 62, 62)
                .addComponent(ButtonDelete)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(LabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(LabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(LabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(LabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(InputUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(InputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(InputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFirstName)
                    .addComponent(LabelLastName)
                    .addComponent(LabelEmail)
                    .addComponent(LabelPhone)
                    .addComponent(LabelUserName)
                    .addComponent(LabelPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInsert)
                    .addComponent(ButtonUpdate)
                    .addComponent(ButtonSearch)
                    .addComponent(ButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogin)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
 
    private void initDatabase(){
        try{
            String url = "jdbc:mysql://localhost:3306/mysql";
            String user = "root";
            String password = "";
            
            conn = DriverManager.getConnection(url, user, password);
            if (conn != null){
                System.out.println("Connect to Database");
            }else{
                System.out.println("Failed connect to database");
            }
        } catch (SQLException e){
            System.out.println("SQL Exception" + e.getMessage());
        
        }
        
    }
    private void populateTable() {
    try {
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM account");

        DefaultTableModel model = (DefaultTableModel) TableListUser.getModel();
        model.setRowCount(0);
        Object[] row;
        while (rs.next()) {
            row = new Object[6];
            row[0] = rs.getString("firstname");
            row[1] = rs.getString("lastname");
            row[2] = rs.getString("email");
            row[3] = rs.getString("phone");
            row[4] = rs.getString("username" );
            row[5] = rs.getString("password");
            model.addRow(row);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    
            
    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void InputUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputUserNameActionPerformed

    private void ButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertActionPerformed
        // TODO add your handling code here:
        String FirstName = InputFirstName.getText();
        String LastName = InputLastName.getText();
        String Email = InputEmail.getText();
        String Phone = InputPhone.getText();
        String UserName = InputUserName.getText();
        String Password = InputPassword.getText();
        DefaultTableModel dataModel = (DefaultTableModel)TableListUser.getModel();
        String list[] = {FirstName, LastName, Email, Phone, UserName, Password};
        
        dataModel.addRow(list);
         String sql = " insert into account (firstname, lastname, email, phone, username, password )"
    + " values (?, ?, ?, ?, ?,?)";
         try{
             
         
           PreparedStatement preparedStmt = conn.prepareStatement(sql);
           preparedStmt.setString(1, FirstName);
           preparedStmt.setString(2, LastName);
           preparedStmt.setString(3, Email);
           preparedStmt.setString(4, Phone);
           preparedStmt.setString(5, UserName);
           preparedStmt.setString(6, Password);
           
           preparedStmt.execute();
         } catch (SQLException e)
  {
  System.err.println("Got an exception!");
  // printStackTrace method 
  // prints line numbers + call stack
  //e.printStackTrace();
  // Prints what exception has been thrown 
  System.out.println(e); 
  }
    }//GEN-LAST:event_ButtonInsertActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = TableListUser.getSelectedRow();
    
    if (selectedRow != -1) {
        String username = (String) TableListUser.getValueAt(selectedRow, 4);
        
        try {
            // Buat kueri SQL DELETE
            String sql = "DELETE FROM account WHERE username = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, username);
            int rowsDeleted = stmt.executeUpdate();
            
            // Hapus baris dari tabel
            DefaultTableModel dataModel = (DefaultTableModel) TableListUser.getModel();
            dataModel.removeRow(selectedRow);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
      
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        String FirstName = InputFirstName.getText();
        //String LastName = InputLastName.getText();
        //String Email = InputEmail.getText();
        //String Phone = InputPhone.getText();
        //String UserName = InputUserName.getText();
        //String Password = InputPassword.getText();
        if(FirstName != ""){
            try {
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM account WHERE firstname ='" + FirstName +"'");

        DefaultTableModel model = (DefaultTableModel) TableListUser.getModel();
        model.setRowCount(0);
        Object[] row;
        while (rs.next()) {
            row = new Object[6];
            row[0] = rs.getString("firstname");
            row[1] = rs.getString("lastname");
            row[2] = rs.getString("email");
            row[3] = rs.getString("phone");
            row[4] = rs.getString("username");
            row[5] = rs.getString("password");
            model.addRow(row);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
        }
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        // TODO add your handling code here:
                        //String sql = "update account  set firstname = '"+ InputFirstName.getText() +"', lastname = '"+ InputLastName.getText()+ "', phone = '" + InputPhone.getText() +"', username = '" + InputUserName.getText() +"', password = '" + InputPassword.getText() +"' Where email = '" + InputEmail.getText() +"'";
                        String sql = "update account set firstname = ?, lastname = ?, phone = ?, username = ?, password = ? WHERE email = ? ";
                        try{ 
             //System.out.println(sql);
             //Statement stmt = conn.createStatement();
             //stmt.executeUpdate(sql);
             
         
           PreparedStatement preparedStmt = conn.prepareStatement(sql);
           preparedStmt.setString(1, InputFirstName.getText());
           preparedStmt.setString(2, InputLastName.getText());
           preparedStmt.setString(3, InputPhone.getText());
           preparedStmt.setString(4, InputUserName.getText());
           preparedStmt.setString(5, InputPassword.getText());
           preparedStmt.setString(6, InputEmail.getText());
           
           int rowsUpdate = preparedStmt.executeUpdate();
           if(rowsUpdate > 0){
               JOptionPane.showMessageDialog(null, "Success", "confirmation", HEIGHT);
           } else{
               System.out.println("error");
           }
             populateTable();  
         } catch (SQLException e)
             {
  System.err.println("Got an exception!");
  // printStackTrace method 
  // prints line numbers + call stack
  //e.printStackTrace();
  // Prints what exception has been thrown 
  System.out.println(e); 
             } 
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void TableListUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListUserMouseClicked
        // TODO add your handling code here:
        int viewRow = TableListUser.getSelectedRow(); 
                int modelRow = TableListUser.convertRowIndexToModel(viewRow);
                Object FirstName = TableListUser.getModel().getValueAt(modelRow, 0);
                this.InputFirstName.setText(FirstName.toString());
 
                Object LastName = TableListUser.getModel().getValueAt(modelRow, 1);
                this.InputLastName.setText(LastName.toString());
                
                Object Email = TableListUser.getModel().getValueAt(modelRow, 2);
                this.InputEmail.setText(Email.toString());
                
                Object Phone = TableListUser.getModel().getValueAt(modelRow, 3);
                this.InputPhone.setText(Phone.toString());
                
                Object UserName = TableListUser.getModel().getValueAt(modelRow, 4);
                this.InputUserName.setText(UserName.toString());
                
                Object Password = TableListUser.getModel().getValueAt(modelRow, 5);
                this.InputPassword.setText(Password.toString());
    }//GEN-LAST:event_TableListUserMouseClicked

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        secion secion = new secion();
        secion.setVisible(true);
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }
    //encapsulation implementasion to access atribute private
    public Connection getConn(){
        return this.conn;
    }
    //encapsulation implementasion to set atribute private
    public void setConn(Connection c){
        this.conn = c;
    }
    private Connection conn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonInsert;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputFirstName;
    private javax.swing.JTextField InputLastName;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JTextField InputPhone;
    private javax.swing.JTextField InputUserName;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelFirstName;
    private javax.swing.JLabel LabelLastName;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JLabel LabelUserName;
    private javax.swing.JTable TableListUser;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}